"""added image

Revision ID: b24216b1872d
Revises: 5de655da7045
Create Date: 2022-05-03 00:10:13.330496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24216b1872d'
down_revision = '5de655da7045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'image_url')
    # ### end Alembic commands ###
