"""added favourite

Revision ID: fb531382ef79
Revises: b24216b1872d
Create Date: 2022-05-03 01:01:48.135206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb531382ef79'
down_revision = 'b24216b1872d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('favourite', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'favourite')
    # ### end Alembic commands ###
